processor_class: echo_processor.EchoChatProcessor
agent_type: python
runtime_version: "3.10"
name: echo-agent
version: 0.1.0
description: A simple echo agent for Orchael using Python
env:
  ECHO_PREFIX: "Echo (custom): "
  ECHO_UPPERCASE: "true"
  ECHO_REPEAT_COUNT: "2"
